name: Push to Docker Hub

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'Dockerfile'
      - 'docker-compose.yml'
      - 'start.sh'
      - '.dockerignore'
      - '.github/workflows/docker-hub-push.yml'
      - '.github/workflows/docker-publish.yml'

env:
  IMAGE_NAME: ghcr.io/w111a/gupax-docker

jobs:
  push-to-dockerhub:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read

    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pull image
        run: |
          docker pull ${{ env.IMAGE_NAME }}:latest

      - name: Tag and push all
        run: |
          VERSION=$(docker inspect ${{ env.IMAGE_NAME }}:latest \
            --format '{{ index .Config.Labels "guax.version" }}')
          if [ -z "$VERSION" ]; then
            VERSION="latest"
          fi
          echo "Tagging as: libre7/gupax-docker:${VERSION}"
          docker tag ${{ env.IMAGE_NAME }}:latest "libre7/gupax-docker:${VERSION}"
          docker tag ${{ env.IMAGE_NAME }}:latest libre7/gupax-docker:latest
          docker push "libre7/gupax-docker:${VERSION}" --quiet
          docker push libre7/gupax-docker:latest --quiet
          docker tag ${{ env.IMAGE_NAME }}:latest libre7/gupax-docker:${{ github.sha }}
          docker push libre7/gupax-docker:${{ github.sha }} --quiet
